<?php

return [
    'options' => [
        'Room 1',
        'Room 2',
        'Room 3',
        'Room 4',
        'Room 5',
        'Room 6 (Speech Lab)',
        'Room 8',
        'Room 9',
        'Room 10 (TLE Garments)',
        'Room 11 (Science Lab)',
        'Room 12 (Food)',
        'Room 13 (Food)',
        'Room 14',
        'Room 15',
        'Room 16 A (Computer Lab)',
        'Room 16 B (Computer Lab)',
        'Room 17',
        'Room 18A',
        'Room 18B',
        'Room 19 (Automotive)',
        'Room 20 (Mechanical)',
        'Room 21 (Electronics)',
        'Room 22 (Electronics)',
        'Room 23 (Electrical)',
        'Room 24 (Electrical)',
        'Accreditation Room',
        'Activity Center',
        'Campus Public Information Office',
        'Covered Court',
        'Food Tech New (BTLED)',
        'MIS',
        'New Covered Court 1',
        'New Covered Court 2',
    ],
];
